# Base configs
baseurl: "/portfolio"
url: "http://www.jvines.cl"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-112699998-1"

# UI configs
title: "Photography by Jose Vines"
subtitle: "See the world through my eyes!"
author: "Jose Vines"
bio: "PhD student at Universidad de Chile, Computer Science aficionado, data visualization lover and now photography amateur."
publicise: ""
web_design: "AJ"
email: jose.vines.l@gmail.com
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/charun310"
  instagram: "https://www.instagram.com/jayvains"
  github: "https://www.github.com/jvines"
